//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampBg.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampBg.Web.App_GlobalResources.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add delivery address.
        /// </summary>
        public static string Add_delivery_address {
            get {
                return ResourceManager.GetString("Add_delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to cart.
        /// </summary>
        public static string Added_to_cart {
            get {
                return ResourceManager.GetString("Added_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory..
        /// </summary>
        public static string All_fields_mandatory {
            get {
                return ResourceManager.GetString("All_fields_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article number.
        /// </summary>
        public static string Article_number {
            get {
                return ResourceManager.GetString("Article_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like a company receipt.
        /// </summary>
        public static string Company_receipt {
            get {
                return ResourceManager.GetString("Company_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm order.
        /// </summary>
        public static string Confirm_order {
            get {
                return ResourceManager.GetString("Confirm_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Create_new_account {
            get {
                return ResourceManager.GetString("Create_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGL.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address.
        /// </summary>
        public static string Delivery_address {
            get {
                return ResourceManager.GetString("Delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery addresses.
        /// </summary>
        public static string Delivery_addresses {
            get {
                return ResourceManager.GetString("Delivery_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease quantity.
        /// </summary>
        public static string Descrease_quantity {
            get {
                return ResourceManager.GetString("Descrease_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit delivery address.
        /// </summary>
        public static string Edit_delivery_address {
            get {
                return ResourceManager.GetString("Edit_delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered.
        /// </summary>
        public static string Email_already_registered {
            get {
                return ResourceManager.GetString("Email_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string External_login_removed {
            get {
                return ResourceManager.GetString("External_login_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize order.
        /// </summary>
        public static string Finalize_order {
            get {
                return ResourceManager.GetString("Finalize_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string Forgotten_password {
            get {
                return ResourceManager.GetString("Forgotten_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email containing information on how to obtain your login information was successfully sent. Please check it in the next 5 minutes and follow the instructions..
        /// </summary>
        public static string Forgotten_password_token_sent {
            get {
                return ResourceManager.GetString("Forgotten_password_token_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as.
        /// </summary>
        public static string Logged_in_as {
            get {
                return ResourceManager.GetString("Logged_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage account.
        /// </summary>
        public static string Manage_account {
            get {
                return ResourceManager.GetString("Manage_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string Manufacturers {
            get {
                return ResourceManager.GetString("Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address.
        /// </summary>
        public static string New_address {
            get {
                return ResourceManager.GetString("New_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New products.
        /// </summary>
        public static string New_products {
            get {
                return ResourceManager.GetString("New_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an address.
        /// </summary>
        public static string No_address {
            get {
                return ResourceManager.GetString("No_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a city.
        /// </summary>
        public static string No_city {
            get {
                return ResourceManager.GetString("No_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name.
        /// </summary>
        public static string No_name {
            get {
                return ResourceManager.GetString("No_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No phone number.
        /// </summary>
        public static string No_phone_number {
            get {
                return ResourceManager.GetString("No_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a postal code.
        /// </summary>
        public static string No_postal_code {
            get {
                return ResourceManager.GetString("No_postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string No_results {
            get {
                return ResourceManager.GetString("No_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string Order_by {
            get {
                return ResourceManager.GetString("Order_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order history.
        /// </summary>
        public static string Order_history {
            get {
                return ResourceManager.GetString("Order_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        public static string Order_id {
            get {
                return ResourceManager.GetString("Order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully placed your order! Your order id is {0}. You should receive a confirmation email in the next 5-10 minutes..
        /// </summary>
        public static string Order_placed {
            get {
                return ResourceManager.GetString("Order_placed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Password_changed_successfully {
            get {
                return ResourceManager.GetString("Password_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Pasword_set_successfully {
            get {
                return ResourceManager.GetString("Pasword_set_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string Payment_method {
            get {
                return ResourceManager.GetString("Payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular categories.
        /// </summary>
        public static string Popular_categories {
            get {
                return ResourceManager.GetString("Popular_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular products.
        /// </summary>
        public static string Popular_products {
            get {
                return ResourceManager.GetString("Popular_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string Postal_code {
            get {
                return ResourceManager.GetString("Postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products by {0}.
        /// </summary>
        public static string Products_by {
            get {
                return ResourceManager.GetString("Products_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products in {0} - {1} - {2}.
        /// </summary>
        public static string Products_in_sub_option {
            get {
                return ResourceManager.GetString("Products_in_sub_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products in {0} - {1}.
        /// </summary>
        public static string Products_in_subcat {
            get {
                return ResourceManager.GetString("Products_in_subcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently viewed.
        /// </summary>
        public static string Recently_viewed {
            get {
                return ResourceManager.GetString("Recently_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register if you don&apos;t have an account..
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related products.
        /// </summary>
        public static string Related_products {
            get {
                return ResourceManager.GetString("Related_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_results {
            get {
                return ResourceManager.GetString("Search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        public static string Shopping_cart {
            get {
                return ResourceManager.GetString("Shopping_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shopping cart is empty..
        /// </summary>
        public static string Shopping_cart_empty {
            get {
                return ResourceManager.GetString("Shopping_cart_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Simple_register {
            get {
                return ResourceManager.GetString("Simple_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        public static string Social_networks {
            get {
                return ResourceManager.GetString("Social_networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirmation.
        /// </summary>
        public static string To_confirmation {
            get {
                return ResourceManager.GetString("To_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
